
export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const ADMIN_CATEGORY_REQUEST = "ADMIN_CATEGORY_REQUEST"
export const ADMIN_CATEGORY_SUCCESS = "ADMIN_CATEGORY_SUCCESS"
export const ADMIN_CATEGORY_FAIL = "ADMIN_CATEGORY_FAIL"

export const  NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const  NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const  NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";
export const  NEW_CATEGORY_RESET = "NEW_CATEGORY_RESET";

export const  UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const  UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const  UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
export const  UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";

export const  DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const  DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const  DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const  DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";

export const  CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const  CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
export const  CATEGORY_DETAILS_FAIL = "CATEGORY_DETAILS_FAIL";

export const  BANNER_REQUEST = "BANNER_REQUEST"
export const  BANNER_SUCCESS = "BANNER_SUCCESS"
export const  BANNER_FAIL = "BANNER_FAIL"

export const  NEW_BANNER_REQUEST = "NEW_BANNER_REQUEST"
export const  NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS"
export const  NEW_BANNER_FAIL = "NEW_BANNER_FAIL"
export const  NEW_BANNER_RESET = "NEW_BANNER_RESET"

export const UPDATE_BANNER_REQUEST = "UPDATE_BANNER_REQUEST";
export const UPDATE_BANNER_SUCCESS = "UPDATE_BANNER_SUCCESS";
export const UPDATE_BANNER_RESET = "UPDATE_BANNER_RESET";
export const UPDATE_BANNER_FAIL = "UPDATE_BANNER_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const BANNER_DETAILS_REQUEST = "BANNER_DETAILS_REQUEST";
export const BANNER_DETAILS_SUCCESS = "BANNER_DETAILS_SUCCESS";
export const BANNER_DETAILS_FAIL = "BANNER_DETAILS_FAIL";

export const ADMIN_PRESCRIPTION_REQUEST = "ADMIN_PRESCRIPTION_REQUEST"
export const ADMIN_PRESCRIPTION_SUCCESS = "ADMIN_PRESCRIPTION_SUCCESS"
export const ADMIN_PRESCRIPTION_FAIL = "ADMIN_PRESCRIPTION_FAIL"

export const NEW_PRESCRIPTION_REQUEST =" NEW_PRESCRIPTION_REQUEST"
export const NEW_PRESCRIPTION_SUCCESS =" NEW_PRESCRIPTION_SUCCESS"
export const NEW_PRESCRIPTION_FAIL =" NEW_PRESCRIPTION_FAIL"
export const NEW_PRESCRIPTION_RESET =" NEW_PRESCRIPTION_RESET"

export const DELETE_PRESCRIPTION_REQUEST =" DELETE_PRESCRIPTION_REQUEST"
export const DELETE_PRESCRIPTION_SUCCESS =" DELETE_PRESCRIPTION_SUCCESS"
export const DELETE_PRESCRIPTION_FAIL =" DELETE_PRESCRIPTION_FAIL"
export const DELETE_PRESCRIPTION_RESET =" DELETE_PRESCRIPTION_RESET"

export const PRESCRIPTION_DETAILS_REQUEST = " PRESCRIPTION_DETAILS_REQUEST"
export const PRESCRIPTION_DETAILS_SUCCESS = " PRESCRIPTION_DETAILS_SUCCESS"
export const PRESCRIPTION_DETAILS_FAIL = " PRESCRIPTION_DETAILS_FAIL"

 
export const CLEAR_ERRORS = "CLEAR_ERRORS";
