
export const ADMIN_TEST_REQUEST = "ADMIN_TEST_REQUEST";
export const ADMIN_TEST_SUCCESS = "ADMIN_TEST_SUCCESS";
export const ADMIN_TEST_FAIL = "ADMIN_TEST_FAIL";

export const NEW_TEST_REQUEST = "NEW_TEST_REQUEST";
export const NEW_TEST_SUCCESS = "NEW_TEST_SUCCESS";
export const NEW_TEST_FAIL = "NEW_TEST_FAIL";
export const NEW_TEST_RESET = "NEW_TEST_RESET";

export const UPDATE_TEST_REQUEST = "UPDATE_TEST_REQUEST";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";
export const UPDATE_TEST_RESET = "UPDATE_TEST_RESET";
export const UPDATE_TEST_FAIL = "UPDATE_TEST_FAIL";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_RESET = "DELETE_TEST_RESET";
export const DELETE_TEST_FAIL = "DELETE_TEST_FAIL";

export const TEST_DETAILS_REQUEST = "TEST_DETAILS_REQUEST";
export const TEST_DETAILS_SUCCESS = "TEST_DETAILS_SUCCESS";
export const TEST_DETAILS_FAIL = "TEST_DETAILS_FAIL";


export const ADMIN_PACKAGE_REQUEST = "ADMIN_PACKAGE_REQUEST";
export const ADMIN_PACKAGE_SUCCESS = "ADMIN_PACKAGE_SUCCESS";
export const ADMIN_PACKAGE_FAIL = "ADMIN_PACKAGE_FAIL";

export const NEW_PACKAGE_REQUEST = "NEW_PACKAGE_REQUEST";
export const NEW_PACKAGE_SUCCESS = "NEW_PACKAGE_SUCCESS";
export const NEW_PACKAGE_FAIL = "NEW_PACKAGE_FAIL";
export const NEW_PACKAGE_RESET = "NEW_PACKAGE_RESET";

export const UPDATE_PACKAGE_REQUEST = "UPDATE_PACKAGE_REQUEST";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_RESET = "UPDATE_PACKAGE_RESET";
export const UPDATE_PACKAGE_FAIL = "UPDATE_PACKAGE_FAIL";

export const DELETE_PACKAGE_REQUEST = "DELETE_PACKAGE_REQUEST";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_RESET = "DELETE_PACKAGE_RESET";
export const DELETE_PACKAGE_FAIL = "DELETE_PACKAGE_FAIL";

export const PACKAGE_DETAILS_REQUEST = "PACKAGE_DETAILS_REQUEST";
export const PACKAGE_DETAILS_SUCCESS = "PACKAGE_DETAILS_SUCCESS";
export const PACKAGE_DETAILS_FAIL = "PACKAGE_DETAILS_FAIL";




export const ALL_PACKAGE_REVIEW_REQUEST = "ALL_PACKAGE_REVIEW_REQUEST";
export const ALL_PACKAGE_REVIEW_SUCCESS = "ALL_PACKAGE_REVIEW_SUCCESS";
export const ALL_PACKAGE_REVIEW_FAIL = "ALL_PACKAGE_REVIEW_FAIL";

export const DELETE_PACKAGE_REVIEW_REQUEST = "DELETE_PACKAGE_REVIEW_REQUEST";
export const DELETE_PACKAGE_REVIEW_SUCCESS = "DELETE_PACKAGE_REVIEW_SUCCESS";
export const DELETE_PACKAGE_REVIEW_RESET = "DELETE_PACKAGE_REVIEW_RESET";
export const DELETE_PACKAGE_REVIEW_FAIL = "DELETE_PACKAGE_REVIEW_FAIL";

export const ADMIN_LABCATEGORY_REQUEST = "ADMIN_LABCATEGORY_REQUEST"
export const ADMIN_LABCATEGORY_SUCCESS = "ADMIN_LABCATEGORY_SUCCESS"
export const ADMIN_LABCATEGORY_FAIL = "ADMIN_LABCATEGORY_FAIL"

export const  NEW_LABCATEGORY_REQUEST = "NEW_LABCATEGORY_REQUEST";
export const  NEW_LABCATEGORY_SUCCESS = "NEW_LABCATEGORY_SUCCESS";
export const  NEW_LABCATEGORY_FAIL = "NEW_LABCATEGORY_FAIL";
export const  NEW_LABCATEGORY_RESET = "NEW_LABCATEGORY_RESET";

export const  UPDATE_LABCATEGORY_REQUEST = "UPDATE_LABCATEGORY_REQUEST";
export const  UPDATE_LABCATEGORY_SUCCESS = "UPDATE_LABCATEGORY_SUCCESS";
export const  UPDATE_LABCATEGORY_FAIL = "UPDATE_LABCATEGORY_FAIL";
export const  UPDATE_LABCATEGORY_RESET = "UPDATE_LABCATEGORY_RESET";

export const  DELETE_LABCATEGORY_REQUEST = "DELETE_LABCATEGORY_REQUEST";
export const  DELETE_LABCATEGORY_SUCCESS = "DELETE_LABCATEGORY_SUCCESS";
export const  DELETE_LABCATEGORY_FAIL = "DELETE_LABCATEGORY_FAIL";
export const  DELETE_LABCATEGORY_RESET = "DELETE_LABCATEGORY_RESET";

export const  LABCATEGORY_DETAILS_REQUEST = "LABCATEGORY_DETAILS_REQUEST";
export const  LABCATEGORY_DETAILS_SUCCESS = "LABCATEGORY_DETAILS_SUCCESS";
export const  LABCATEGORY_DETAILS_FAIL = "LABCATEGORY_DETAILS_FAIL";

export const SAMPLE_REQUEST = "SAMPLE_REQUEST"
export const SAMPLE_SUCCESS = "SAMPLE_SUCCESS"
export const SAMPLE_FAIL = "SAMPLE_FAIL"

export const  NEW_SAMPLE_REQUEST = "NEW_SAMPLE_REQUEST";
export const  NEW_SAMPLE_SUCCESS = "NEW_SAMPLE_SUCCESS";
export const  NEW_SAMPLE_FAIL = "NEW_SAMPLE_FAIL";
export const  NEW_SAMPLE_RESET = "NEW_SAMPLE_RESET";

export const  UPDATE_SAMPLE_REQUEST = "UPDATE_SAMPLE_REQUEST";
export const  UPDATE_SAMPLE_SUCCESS = "UPDATE_SAMPLE_SUCCESS";
export const  UPDATE_SAMPLE_FAIL = "UPDATE_SAMPLE_FAIL";
export const  UPDATE_SAMPLE_RESET = "UPDATE_SAMPLE_RESET";

export const  DELETE_SAMPLE_REQUEST = "DELETE_SAMPLE_REQUEST";
export const  DELETE_SAMPLE_SUCCESS = "DELETE_SAMPLE_SUCCESS";
export const  DELETE_SAMPLE_FAIL = "DELETE_SAMPLE_FAIL";
export const  DELETE_SAMPLE_RESET = "DELETE_SAMPLE_RESET";

export const  SAMPLE_DETAILS_REQUEST = "SAMPLE_DETAILS_REQUEST";
export const  SAMPLE_DETAILS_SUCCESS = "SAMPLE_DETAILS_SUCCESS";
export const  SAMPLE_DETAILS_FAIL = "SAMPLE_DETAILS_FAIL";


// export const  BANNER_REQUEST = "BANNER_REQUEST"
// export const  BANNER_SUCCESS = "BANNER_SUCCESS"
// export const  BANNER_FAIL = "BANNER_FAIL"

// export const  NEW_BANNER_REQUEST = "NEW_BANNER_REQUEST"
// export const  NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS"
// export const  NEW_BANNER_FAIL = "NEW_BANNER_FAIL"
// export const NEW_BANNER_RESET = "NEW_BANNER_RESET"
 
export const CLEAR_ERRORS = "CLEAR_ERRORS";
